### ISSUE TITLE
Plugin dependencies include multiple slf4j bindings

### ISSUE THREAD

**Issue by rktoomey** [sbt/sbt-bintray#107]
When I included just the plugin in my `plugins.sbt`:

```
addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.4.0")
```

I got SLF4J whining about multiple bindings on the classpath:

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/rosetoomey/.ivy2/cache/org.slf4j/slf4j-simple/jars/slf4j-simple-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/rosetoomey/.ivy2/cache/org.slf4j/slf4j-nop/jars/slf4j-nop-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```

This fixed it:

```
addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.4.0"
	exclude("org.slf4j", "slf4j-nop")
)
```

**Comment by rktoomey** [comment]
Suggested refactor: depend on `slf4j-api` in the plugin and then document that in `plugins.sbt` the caller should provide an impl like this:

```
libraryDependencies ++= Seq(
  "org.slf4j" % "slf4j-simple" % "1.7.22"  // or slf4j-nop
)

addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.4.1")
```

**Comment by eed3si9n** [comment]
Thanks for the report. I'll look into where these are coming from.

**Comment by rktoomey** [comment]
Thanks @eed3si9n, happy to help test it out.  I observed this in a new project I was setting up, before adding any other dependencies but I did have two other plugins:

```
addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.6.0")

addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.4.0"
	exclude("org.slf4j", "slf4j-nop")
)

addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
```

I didn't see any SLF4J errors until I added the sbt-bintray plugin and reloaded.  I'll try removing the other two plugins as well as the `exclude`, exiting sbt, recursively deleting all my target dirs, and confirm that the error still shows up.  Does sbt-dependency-graph work on plugin deps or only project deps?:

**Comment by jvican** [comment]
@rktoomey I think these exclusions are legit. Do you happen to have sfl4j as a dependency in a global sbt file? I've seen several people have a library dependency because of scalatest (or a test framework whose name I don't remember now).

**Comment by rktoomey** [comment]
@jvican No, this project was completely new, I hadn't added any dependencies yet, I was just getting a bare framework setup

**Comment by 2m** [comment]
The `slf4j-nop` was added in https://github.com/sbt/sbt-bintray/issues/26 

We can remove it but then we need to make sure that there is no noisy warnings printed out during the startup as reported in #26.
