### ISSUE TITLE
publish sbt 1.0.0 version

### ISSUE THREAD

**Issue by Elufimov** [sbt/sbt-bintray#129]
addSbtPlugin("org.foundweekends" % "bintray-sbt" % "0.5.1") does not work under sbt 1.0.0

**Comment by xuwei-k** [comment]
What kind of errors?

**Comment by dwijnand** [comment]
It's `addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.1")` - note it switched to "sbt-bintray".
