### ISSUE TITLE
This plugin should not be automatically triggered

### ISSUE THREAD

**Issue by sjrd** [sbt/sbt-bintray#130]
This part of sbt-bintray irks me:
```scala
  override def requires = sbt.plugins.JvmPlugin
  override def trigger = allRequirements
```
Because of this, upgrading from bintray-sbt 0.1.2 to sbt-bintray 0.5.1 ([commit here](https://github.com/sjrd/scala-js/commit/a297c674c6cfc7afb5b44b7abf59cb4b76013641)) broke the publishing of all my artifacts that are *not* supposed to be published to Bintray but to Sonatype. Example:
```scala
> ++2.10.6
[info] Setting version to 2.10.6
[info] Reapplying settings...
[info] Set current project to Scala.js (in build file:/localhome/doeraene/projects/scalajs/)
> show sbtPlugin/publishTo
[info] Some(Raw(Bintray-Sbt-Publish-scala-js-scala-js-releases-sbt-scalajs))
> show compiler/publishTo
[info] Some(snapshots: https://oss.sonatype.org/content/repositories/snapshots)
> compiler/publish
[info] Updating {file:/localhome/doeraene/projects/scalajs/}compiler...
[info] Packaging /localhome/doeraene/projects/scalajs/compiler/target/scala-2.10/scalajs-compiler_2.10.6-0.6.20-SNAPSHOT-sources.jar ...
[info] Wrote /localhome/doeraene/projects/scalajs/compiler/target/scala-2.10/scalajs-compiler_2.10.6-0.6.20-SNAPSHOT.pom
[info] Resolving com.novocode#junit-interface;0.9 ...
[info] Done packaging.
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] :: delivering :: org.scala-js#scalajs-compiler_2.10.6;0.6.20-SNAPSHOT :: 0.6.20-SNAPSHOT :: integration :: Mon Aug 28 13:24:42 CEST 2017
[info]  delivering ivy file to /localhome/doeraene/projects/scalajs/compiler/target/scala-2.10/ivy-0.6.20-SNAPSHOT.xml
[info] Compiling 34 Scala sources to /localhome/doeraene/projects/scalajs/compiler/target/scala-2.10/classes...
[info] Main Scala API documentation to /localhome/doeraene/projects/scalajs/compiler/target/scala-2.10/api...
model contains 248 documentable templates
[warn] [...]
[warn] one warning found
[info] Main Scala API documentation successful.
[info] Packaging /localhome/doeraene/projects/scalajs/compiler/target/scala-2.10/scalajs-compiler_2.10.6-0.6.20-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[warn] two warnings found
[info] Packaging /localhome/doeraene/projects/scalajs/compiler/target/scala-2.10/scalajs-compiler_2.10.6-0.6.20-SNAPSHOT.jar ...
[info] Done packaging.
[info]  published scalajs-compiler_2.10.6 to https://oss.sonatype.org/content/repositories/snapshots/org/scala-js/scalajs-compiler_2.10.6/0.6.20-SNAPSHOT/scalajs-compiler_2.10.6-0.6.20-SNAPSHOT.pom
[info]  published scalajs-compiler_2.10.6 to https://oss.sonatype.org/content/repositories/snapshots/org/scala-js/scalajs-compiler_2.10.6/0.6.20-SNAPSHOT/scalajs-compiler_2.10.6-0.6.20-SNAPSHOT.jar
[info]  published scalajs-compiler_2.10.6 to https://oss.sonatype.org/content/repositories/snapshots/org/scala-js/scalajs-compiler_2.10.6/0.6.20-SNAPSHOT/scalajs-compiler_2.10.6-0.6.20-SNAPSHOT-sources.jar
[info]  published scalajs-compiler_2.10.6 to https://oss.sonatype.org/content/repositories/snapshots/org/scala-js/scalajs-compiler_2.10.6/0.6.20-SNAPSHOT/scalajs-compiler_2.10.6-0.6.20-SNAPSHOT-javadoc.jar
[trace] Stack trace suppressed: run last compiler/*:bintrayRelease for the full output.
[error] (compiler/*:bintrayRelease) failed to release sjrd/scalajs-compiler@0.6.20-SNAPSHOT: {"message":"Version '0.6.20-SNAPSHOT' was not found"}
[error] Total time: 23 s, completed Aug 28, 2017 1:25:03 PM
```
I specifically set `publishTo :=` in non-Bintray artifacts, so `show compiler/publishTo` correctly shows oss.sonatype.org. However, doing `compiler/publish`, after correctly publishing to Sonatype, still insists on doing `bintrayRelease` which fails.

An `AutoPlugin` that alters existing keys must not be automatically triggered. It must be opt-in. It's not because I need sbt-bintray for some artifacts in my build that I want it for *all* of them.

(I guess using `disablePlugins(BintrayPlugin)` on all my other `project`s would be a workaround.)

**Comment by eed3si9n** [comment]
I made this a triggered plugin in https://github.com/sbt/sbt-bintray/commit/42fd6a869e3e60dc840ee213d055d7696d3f24b8 in 2015 apparently. The thinking was that most plugin projects are single subproject build that all publish to Bintray.

For a few hybrid build with mix of Sonatype and Bintray I've seen `disablePlugins(...)` basically.

- Giter8 https://github.com/foundweekends/giter8/blob/29d329bb92977a7848e8b48bd2ba5d1cf551e210/build.sbt#L104
- Paradox https://github.com/lightbend/paradox/blob/2b47d89f56a5b5c74d59884bff0abe4480ae7c0a/build.sbt#L38
- Contraband https://github.com/sbt/contraband/blob/67a2a7344c1d879f9b9a9fd15c53481ce36c4724/build.sbt#L37

**Comment by sjrd** [comment]
Even if I agree that most plugin builds would be single-project, I think the following motto should be a golden rule observed by all sbt plugins: if an `AutoPlugin` alters any existing behavior in a way that can potentially be incompatible with the non-altered version, it should not be auto-triggered.

If we agree that the above rule is a desirable state for the sbt plugin ecosystem, here is a sketch for a migration path for this plugin to comply:
1. Declare a separate `AutoTriggeredBintrayPlugin`, which is auto-triggered (like the current one) and applies all the settings that the current one applies.
2. In the settings of that plugin, somewhere have an `sLog.warn("Auto-triggering of BintrayPlugin is deprecated. Please add .enablePlugins(BintrayPlugin) to your projects")`.
3. Turn `BintrayPlugin` into a non-triggered plugin, which requires `AutoTriggeredBintrayPlugin`. That plugin overrides the setting that does `sLog.warn()` above so that it *doesn't* do the `warn`.

Release a patch version with those changes, then in 0.6.0, get rid of `AutoTriggeredBintrayPlugin` and put the settings only in `BintrayPlugin`, which is not auto-triggered.

**Comment by eed3si9n** [comment]
`AutoTriggeredBintrayPlugin` would automatically kick in if it's part of "sbt-bintray" module, so a better path might be:

1. add `BintrayOptionalPlugin` as a separate JAR called "sbt-bintray-optional", and move most of the code there.
2. `BintrayPlugin` and "sbt-bintray" stays a triggered plugin, which internally depends on "sbt-bintray-optional".

**Comment by sjrd** [comment]
> AutoTriggeredBintrayPlugin would automatically kick in if it's part of "sbt-bintray" module

That's kind of the point of my proposal ;) Maybe you read it too fast?

Anyway your proposal is equally good, and possibly easier to implement.

**Comment by eed3si9n** [comment]
>  then in 0.6.0, get rid of AutoTriggeredBintrayPlugin and put the settings only in BintrayPlugin,

Yes. I missed the part where you get rid of the AutoTriggeredBintrayPlugin in 0.6.0.

**Comment by aappddeevv** [comment]
I think the readme should be updated. I was surprised when the plugin tried to publish my docs and examples sub-projects which are not meant to be published and been marked as "not to published." I went ahead and removed the plugins for those two projects per the links, but that was a bit counterintuitive.
