### ISSUE TITLE
Task to prune uploaded snapshots

### ISSUE THREAD

**Issue by raboof** [sbt/sbt-bintray#154]
When also publishing nighly snapshots to bintray (using a version convention such as https://github.com/dwijnand/sbt-dynver), it would be nice to add a task that gets the versions from bintray (https://bintray.com/docs/api/#_get_package) and deletes (https://bintray.com/docs/api/#url_delete_version) all old snapshots except but a configurable number of most-recent ones?

For example if there's `1.2.3-1`, `1.2.3-2`, `1.2.3-3` and `1.2.4-1` and we keep 2, we should keep `1.2.3-3` and `1.2.4-1`

**Comment by ennru** [comment]
I just successfully used `bintrayUnpublish` to clean up snapshots:
`; set version in ThisBuild := "0.19+10-4995b08b" ; bintrayUnpublish`

So combined with listing versions known by Bintray this could become usable, I guess.
