### ISSUE TITLE
Gitter access

### ISSUE THREAD

**Issue by Synesso** [sbt/sbt-bintray#158]
https://gitter.im/sbt/sbt-bintray provides a message that "only github users can join this room".

I am a github user.

Other channels in the scala ecosystem are fine for me.

Perhaps the sbt-bintray channel needs a setting relaxed?

**Comment by Synesso** [comment]
I was able to join the room by clicking "add", searching for myself and then refreshing the page.

**Comment by 2m** [comment]
Thanks for the heads-up! I found a checkbox in the sbt-bintray room settings where it prevented non-github users joining the room. I have unchecked that box now.
