### ISSUE TITLE
A question about publishing sbt-plugins

### ISSUE THREAD

**Issue by denisftw** [sbt/sbt-bintray#16]
Hello!

I'm trying to publish a forked Play! plugin, which I believe can be regarded as an sbt-plugin here, to my repository on Bintray. I experimented with both maven-style and ivy-style publishing and it kind of works:

When I specify `sbtPlugin := true`, `publishMavenStyle := false` and use my generic (in terms of Bintray) repository `sbt-plugins`, it publishes the artifact using the Ivy pattern. 

https://github.com/denisftw/securesocial/blob/c13e45ce9128e533c6caa378075c7f9e43fa7ac3/module-code/build.sbt

So, my artifact ends up at 

/denisftw/sbt-plugins/denisftw/securesocial/scala_2.10/sbt_0.13/0.0.1/jars/

Then I use it as a dependency in another project and specify my repository with the Resolver.ivyStylePatterns option. However, sbt cannot download it and apparently it expects the ivy file at slightly different address. 

When I use Mike Slinn's fork of the same plugin, everything works just fine. Besides, his artifacts are here:

/sbt/sbt-plugin-releases/com.micronautics/securesocial/2.2.0/jars/

Maybe it has something to do with inserting scala and sbt versions in the path? Can I influence the plugin use my pattern during the publishing phase ?

Thanks

**Comment by 2m** [comment]
The original issue was cleared up.
