### ISSUE TITLE
default bintrayVcsUrl is not a URL

### ISSUE THREAD

**Issue by lJoublanc** [sbt/sbt-bintray#163]
The default value for `bintrayVcsUrl` introduced in #46 appears to not follow the URL RFC spec:

```
sbt:scodec-bson> show bintrayVcsUrl
[info] Some(git@gitlab.com:lJoublanc/scodec-bson.git)
```

This doesn't prevent publishing. However, when from the bintray web-interface you try to add your project to JCenter and Maven Central, you get an error as a result of this. See [this stackoverflow question](https://stackoverflow.com/questions/52774251/link-public-github-repo-on-bintray-to-jcenter) for more detail. It points out that on the webpage the tooltip says this should be a 'valid URL'.

The value that is set here also appears to be publicly visible on the bintray website, and is an `href` link, which leads me to believe that it should start with `http[s]://` as per the SO question. However, changing this to e.g. `git://git@gitlab.com:lJoublanc/scodec-bson.git` (which is a valid URL according to RFC) appears to work around the 'publishing to maven central' issue in the SO question alone.

The default is currently derived from git [in `resolveVcsUrl`](https://github.com/sbt/sbt-bintray/blob/b2dcc316fa4f8ea701f076516b430292af8c5389/src/main/scala/Bintray.scala#L128-L137).

* Should the default be changed? 
* Should it accept a non-http prefix such as `git://`, as this will be linked on the web UI? 
* Or should we somehow infer `http[s]://` always? Should this work for non-github locations too (e.g. gitlab? what about a local/private repo?)

**Comment by eed3si9n** [comment]
Thanks for the report @lJoublanc. 

sbt has a datatype called `ScmInfo` https://github.com/sbt/librarymanagement/blob/v1.2.4/core/src/main/contraband-scala/sbt/librarymanagement/ScmInfo.scala that lets you hold both URL and connection string.

```
      scmInfo := Some(ScmInfo(url("https://github.com/org/foo"), "git@github.com:org/foo.git")),
```

Maybe `bintrayVcsUrl` should be derived off of that when `scmInfo` has a value, and warn on startup if it doesn't have a value.

**Comment by lJoublanc** [comment]
I received this reply to my query form JFrog support, for the record:

> Thanks for reaching JFrog support.
> With regards to your query,
> The version control URL should be the source code URL of "gitlab" or "github" where it should be accessible to public.
> The gitlab URL "https://gitlab.com/lJoublanc/scodec-bson"  should be "public" and also it should point to the source code of the project.
> Regarding the website, We suggest to keep the same URL  as Version control URL.
