### ISSUE TITLE
publishing always yields: Provided artifact path does not comply with Maven's convention

### ISSUE THREAD

**Issue by swachter** [sbt/sbt-bintray#17]
Publishing using the `publish` command always yields the error:

[error](core/*:publish) error uploading to https://api.bintray.com/maven/swachter/generic/core/eu/swdev/playext/core_2.10/0.1-SNAPSHOT/core_2.10-0.1-SNAPSHOT.pom: {"message":"Provided artifact path does not comply with Maven's convention"}

I use the following settings related to bintray-sbt:

```
bintraySettings ++ Seq(
    licenses += ("MIT", url("http://opensource.org/licenses/MIT")),
    publishMavenStyle := true,
    bintray.Keys.repository in bintray.Keys.bintray := "generic",
    bintray.Keys.bintrayOrganization in bintray.Keys.bintray := None,
    bintray.Keys.packageLabels in bintray.Keys.bintray := Seq("Scala", "Play")
)
```

I tried various combinations for publishMavenStyle = true/false and for repository = generic/maven without success.

The complete build.sbt can be found at: https://github.com/swachter/play-macro-form/blob/master/build.sbt. The error occurs when I try to publish while being inside the `core` project.

**Comment by JohnMurray** [comment]
Ditto. Just ran into this. A year later, but still relevant.

**Comment by olafurpg** [comment]
Same error here, SNAPSHOT was the issue. Thanks!

**Comment by acjay** [comment]
Also curious, how should snapshots be published?

**Comment by 2m** [comment]
Closing the ticket, as the original issue seems to not be relevant anymore. As to strategy for publishing snapshots, use the following ticket for discussions: https://github.com/sbt/sbt-bintray/issues/20

**Comment by guizmaii** [comment]
https://github.com/sbt/sbt-bintray/issues/20#issuecomment-659139541
