### ISSUE TITLE
'bintrayChangeCredentials' doesn't work under sbt 1.3.3

### ISSUE THREAD

**Issue by unoexperto** [sbt/sbt-bintray#177]
Looks like 'bintrayChangeCredentials' doesn't work under sbt 1.3.3. It probably has to do with the way new sbt works with console UI. It just hangs and you can't even terminate the process with Ctrl-C.

**Comment by TonioGela** [comment]
I can confirm that, a workaround is setting `ThisBuild / useSuperShell := false` for that build.sbt
