### ISSUE TITLE
crossScalaVersions are not published

### ISSUE THREAD

**Issue by carloscaldas** [sbt/sbt-bintray#185]
Only the package with version defined in sbt is published. Packages created using crossScalaVersions are not published

**Comment by angelcervera** [comment]
Maybe you are using sbt-release with sbt 1.*?

https://www.scala-sbt.org/1.x/docs/Cross-Build.html#Note+about+sbt-release

**Comment by tyrcho** [comment]
seems to be the same issue as #42 

I'm using only sbt-bintray (not sbt-release) and this works for me. See for instance https://gitlab.com/tyrcho/approvals-scala/-/jobs/581669177
