### ISSUE TITLE
Publishing SNAPSHOTS guidelines

### ISSUE THREAD

**Issue by antonkulaga** [sbt/sbt-bintray#20]
Please, provide some guidlines about publishing snapshots.
I am not only talking about https://github.com/softprops/bintray-sbt/issues/17 issue but also about rewriting snapshot in repos ( I do not think that typing "unpublish"comment each time I publish a SNAPSHOT is convenient)

**Comment by eed3si9n** [comment]
My guideline for SNAPSHOT is that it should not be used outside of local testing.

**Comment by guizmaii** [comment]
I ended up released some RC versions.
