### ISSUE TITLE
Provide credentials via build.sbt instead of through a properties file

### ISSUE THREAD

**Issue by timt** [sbt/sbt-bintray#25]
Great plugin,

I'd like to use it to publish from travis-ci.org, but I can't see a way to set the credentials securely when doing that.

Is it possible for me to provide them in my build.sbt, that way I could base them on travis-ci environment variables, which I can then secure in the .travis.yaml?

e.g.

import bintray.Keys._

.....

bintrayUser := timt
bintrayApiKey := Try(sys.env("BINTRAY_API_KEY")).getOrElse("BARF!!!!")

....

where BINTRAY_API_KEY is a value I set through the normal travis-ci "secure" mechanism.

**Comment by pjan** [comment]
+1 for this. Use of the sbt credentials interface would greatly improve the usability of this plugin in a CI environment.

Status or timeline for this?

**Comment by ninjabear** [comment]
+1 this would be really useful

**Comment by mateusduboli** [comment]
+1 This is extremely useful

**Comment by EmilDafinov** [comment]
+1 From me as well, it would be great to be able to specify these in the build.sbt and not rely on a file...

**Comment by 2m** [comment]
Since `0.5.0` because of https://github.com/sbt/sbt-bintray/pull/113 sbt-bintray now gets the credentials from the environment variables as well as system properties: https://github.com/sbt/sbt-bintray#credentials
