### ISSUE TITLE
Do not replace an existing published version

### ISSUE THREAD

**Issue by etaty** [sbt/sbt-bintray#35]
Hi

I should get a warning/error/failure when i try to re publish a version already on bintray.

**Comment by shevek** [comment]
Now 180 days. https://bintray.com/docs/api/#_content_uploading_publishing

**Comment by panpan0000** [comment]
anyone knows why it has 180 days limitation, if we indeed want to use the same version, how to handle it? backup all packages in this version, delete this version, re-create the same version then upload backup packages to this new same name version?
