### ISSUE TITLE
do a better job of documenting sync to maven central feature

### ISSUE THREAD

**Issue by softprops** [sbt/sbt-bintray#40]
including http://central.sonatype.org/pages/requirements.html#sufficient-metadata for sonatype newbies

**Comment by zsxwing** [comment]
Is it possible to read "sona.user" and "sona.pass" from the environment variables? We want to do the maven synchronization using Travis CI. Thank you!

**Comment by 2m** [comment]
@zsxwing yes it is. The plugin looks at `SONA_USER` and `SONA_PASS` env variables as well when looking for credentials for sonatype. This information is lacking in the README.
