### ISSUE TITLE
Publishing multi-module project fails

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-bintray#47]
When trying to publish all modules of https://github.com/hseeberger/akka-http-json by executing "publish" from the root module, only the first of the two submodules gets published and for the second I get 

```
[trace] Stack trace suppressed: run last akkaHttpJsonSpray/*:publish for the full output.
[error] (akkaHttpJsonSpray/*:publish) error uploading to https://api.bintray.com/maven/hseeberger/maven/maven/de/heikoseeberger/akka-http-json-spray_2.11/0.2.0-58a581fde0cc46f83b485a2bb3d0b81eeabf3bc5/akka-http-json-spray_2.11-0.2.0-58a581fde0cc46f83b485a2bb3d0b81eeabf3bc5.pom: <html>
[error] <head><title>405 Not Allowed</title></head>
[error] <body bgcolor="white">
[error] <center><h1>405 Not Allowed</h1></center>
[error] <hr><center>nginx</center>
[error] </body>
[error] </html>
```

Maybe this is not a but of bintray-sbt, but just me. So talking a look at my sbt build would be highly appreciated.

**Comment by betehess** [comment]
I have the same problem with https://github.com/w3c/banana-rdf/tree/wip/publication-settings.

**Comment by netvl** [comment]
Same thing here. I always get 405 Not Allowed error when publishing my project, but strangely, everything seems to be uploaded correctly when I retry `publish` command enough times.

**Comment by eed3si9n** [comment]
Have you tried staging first? - https://github.com/softprops/bintray-sbt#staging-optional

**Comment by netvl** [comment]
This was the first thing I've enabled after upgrading to the latest version - I prefer to release manually after I've checked everything. And indeed, in the latest version there are no `Not Allowed` errors anymore, however, it became awfully slow (#65) to publish anything.
