### ISSUE TITLE
How to include app/ as source directory for publishing Play module

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt-bintray#50]
It's easy to publish a library with source code in src/, but Play modules have their source in app/, and there is no main method. How do I tell bintray-sbt that it should package the compiled output from app/?

[Here is the Play module](https://github.com/mslinn/securesocial/tree/2.1.5) (branch 2.1.5)

**Comment by softprops** [comment]
I think this is more of an sbt question than a bintray-sbt question. There are a number of [keys](https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Keys.scala#L160-L172) sbt uses to determine how to package an set of files that get put into published artifact. I you may have to dig through their [definitions](https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Defaults.scala#L589-L601) for how to include files that Play puts in other locations.

**Comment by mslinn** [comment]
I posted the question on [Gitter for playframework](https://gitter.im/playframework/playframework)

**Comment by 2m** [comment]
This should work out of the box as the same sbt keys are used. Closing this for now. Please feel free to reopen if the issue is still there.
