### ISSUE TITLE
bintrayOrganization key not found in 0.3.0

### ISSUE THREAD

**Issue by velvia** [sbt/sbt-bintray#60]
Following the README, setting `bintrayOrganization := Some("blah")` doesn't work:

```
[error] /Users/evanchan/src/github/spark-jobserver/project/Build.scala:161: not found: value bintrayOrganization
[error]     bintrayOrganization := Some("spark-jobserver")
[error]     ^
```

I have to include the full path instead... the following works: `bintray.BintrayKeys.bintrayOrganization := Some("spark-jobserver")`.

**Comment by velvia** [comment]
I should also note that my `publishTo` settings got reset when I upgraded to 0.3.0.   I downgraded to 0.2.1 and it was fine.

**Comment by jamescway** [comment]
I had to import the keys
```scala
object MyProject extends Build {
  import bintray.BintrayKeys._
```

**Comment by dwijnand** [comment]
Documented in https://github.com/sbt/sbt-bintray/pull/112
