### ISSUE TITLE
Publish should be idempotent

### ISSUE THREAD

**Issue by newhoggy** [sbt/sbt-bintray#63]
If I publish the same version of the same artefact twice, the publish should succeed if the artefact is the same.

Currently, if I publish the same version of the same artefact twice, the publish fails with {"message":"Unable to upload files: An artifact with the path XXXXX already exists"}

**Comment by jvican** [comment]
I don't think this is worth it and should be closed. If you're attempting to release with the same version an artifact, then it's really the user's problem.

**Comment by SethTisue** [comment]
agree

**Comment by 2m** [comment]
Closing as per discussion.
