### ISSUE TITLE
I don't understand how to work with 0.3.0

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt-bintray#68]
v0.2.0 was easy: just add this to `project/whatever.sbt`:

```
resolvers += Resolver.url("bintray-sbt-plugin-releases", url("http://dl.bintray.com/content/sbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)
addSbtPlugin("me.lessis" % "bintray-sbt" % "0.2.0")
```

Then `build.sbt` can contain bintray-specific stuff, such as:

```
import bintray.BintrayKeys._
```

With 0.3.0 the above import fails.I tried commenting out the resolver, but no joy. What is the secret to getting v0.3.0 to work with Scala 2.11.7 and SBT 0.13.8?

**Comment by 2m** [comment]
As [per readme](https://github.com/softprops/bintray-sbt/blob/master/README.md), you only need to add `addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")` to your `project/plugins.sbt` file and sbt autoplugin magic will add all required settings. Then do `sbt publish` to publish.

**Comment by mslinn** [comment]
That is not my experience, as mentioned.

**Comment by 2m** [comment]
You do not need to add the import statement explicitly, because [keys that are defined in `autoImport`](https://github.com/softprops/bintray-sbt/blob/0.3.0/src/main/scala/BintrayPlugin.scala#L20) are imported automatically in `.sbt` files

**Comment by mslinn** [comment]
Omitting the import yields:

    /home/mslinn/work/experiments/play/PFView/build.sbt:32: error: not found: value bintrayPublishSettings

**Comment by 2m** [comment]
You do not need to use `bintrayPublishSettings` as well. Adding `addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")` is the only required change to your project to use this plugin, if you are fine with the default settings. And that is a good starting point in any case.

**Comment by jvican** [comment]
Let's close. This concerns a migration that happened a long while ago.
