### ISSUE TITLE
Exposing bintray functions

### ISSUE THREAD

**Issue by huntc** [sbt/sbt-bintray#76]
Would it be reasonable to make the privately scoped functions of https://github.com/softprops/bintray-sbt/blob/master/src/main/scala/Bintray.scala public and document them?

I'm presently extending [sbt-bintray-bundle](https://github.com/sbt/sbt-bintray-bundle/pull/1) and require access so far to `ensureLicenses`, `ensuredCredentials`, `saveBintrayCredentials` and `requestCredentials`.

Thanks.

**Comment by 2m** [comment]
This looks like not needed anymore. Closing the ticket. Feel free to open a new one, if some APIs should be opened up.
