### ISSUE TITLE
Include information on `bintrayRepository` in README.md

### ISSUE THREAD

**Issue by metasim** [sbt/sbt-bintray#83]
It would be helpful to understand the relationship between `bintrayOrganization` and `bintrayRepository` when publishing, and how it corresponds to `Resolver. bintrayRepo`. IOW, it's not clear from the README how one ensures publishing is routed to a specific repository.

**Comment by dwijnand** [comment]
Done in https://github.com/sbt/sbt-bintray/pull/112
