### ISSUE TITLE
The publish key should not automatically trigger upon plugin import.

### ISSUE THREAD

**Issue by JustinPihony** [sbt/sbt-bintray#88]
The problem here is that when you do something like `addSbtPlugin("com.typesafe.sbt" % "sbt-bintray-bundle" % "1.0.2")`, then run `sbt`, you end up with warnings about a missing bintray credentials file, and cannot even run projects. The bintray credential should not be required unless you actually call `publish`.

Please refer to [this activator template issue for the end issue,](https://github.com/lagom/activator-lagom-java-chirper/issues/26) which is triggered from including [the sbt-bintray-bundle plugin.](https://github.com/sbt/sbt-bintray-bundle/blob/df7f694f02a77e5d97fbe08fb6e9462d8c7fd531/src/main/scala/com/typesafe/sbt/bintraybundle/BintrayBundle.scala#L44) It was determined that the root issue is most likely due to [these lines](https://github.com/softprops/bintray-sbt/blob/master/src/main/scala/BintrayPlugin.scala#L170-L183) being triggered by `publishTo in bintray <<= publishToBintray`

**Comment by bayarmunkh** [comment]
Any workaround on this issue?

Disabling the plugin doesn't seem working . It still complains the creds file is missing.
```scala
(project in file(".")).disablePlugins(BintrayPlugin)
```

**Comment by 2m** [comment]
More discussion about possible improvements in #130
