### ISSUE TITLE
Rename bintray-sbt to sbt-bintray

### ISSUE THREAD

**Issue by soc** [sbt/sbt-bintray#89]
There is tremendous value in having a default naming convention for SBT plugins:
  http://www.scala-sbt.org/1.0/docs/Plugins-Best-Practices.html#Follow+the+naming+conventions

Related changes:
- coursier-sbt-plugin -> sbt-coursier: alexarchambault/coursier#202
- android-sdk-plugin -> sbt-android: https://github.com/scala-android/sbt-android
- sbteclipse-plugin -> sbt-eclipse: typesafehub/sbteclipse#314
- ensime-sbt -> sbt-ensime: https://github.com/ensime/ensime-sbt/issues/182

It would be nice if sbt-bintray could adopt it, maybe with the next version that targets SBT 1.0?

**Comment by eed3si9n** [comment]
Repo name is now changed. We can release the next version using the new name.

**Comment by dwijnand** [comment]
Sitting on master, unreleased is #70 "Ensure that package creation task is executed before publishing". I say a good enough excuse to rename and release as soon as someone has time.

(https://github.com/sbt/sbt-bintray/compare/0.3.0...master)

**Comment by 2m** [comment]
https://github.com/sbt/sbt-bintray/tree/v0.4.0

**Comment by 2m** [comment]
This can be closed now. (I do not have enough permissions to close it myself)
