### ISSUE TITLE
More documentation, please.

### ISSUE THREAD

**Issue by angelcervera** [sbt/sbt-bintray#92]
SBT world is starting to be like the Maven world. That means, poor documentation or not documentation at all. Then, research in the code!

It is really frustrating.

Examples:
- bintrayRepository??
- bintrayPackage??

**Comment by PhilAndrew** [comment]
I was able to publish by https://github.com/sbt/sbt-bintray/issues/94

**Comment by dwijnand** [comment]
More documentation as of https://github.com/sbt/sbt-bintray/pull/112
